import { Agency, Route, Stop, Calendar } from '../../types/transit';

export const SEED_AGENCIES: Agency[] = [
  {
    agency_id: 'MTC',
    agency_name: 'Metropolitan Transport Corporation (Chennai) Ltd.',
    agency_url: 'https://mtcbus.tn.gov.in',
    agency_timezone: 'Asia/Kolkata',
    agency_lang: 'ta,en',
    agency_phone: '044-23455801',
    agency_fare_url: 'https://mtcbus.tn.gov.in/Home/fare',
  },
  {
    agency_id: 'CMRL',
    agency_name: 'Chennai Metro Rail Limited',
    agency_url: 'https://chennaimetrorail.org',
    agency_timezone: 'Asia/Kolkata',
    agency_lang: 'ta,en',
    agency_phone: '1860-425-1515',
    agency_fare_url: 'https://chennaimetrorail.org/fare-calculator/',
  },
];

export const SEED_ROUTES: Route[] = [
  // --- CHENNAI METRO LINES ---
  {
    route_id: 'CMRL-BLUE',
    agency_id: 'CMRL',
    route_short_name: 'Blue Line',
    route_long_name: 'Wimco Nagar Depot ⇄ Chennai International Airport',
    route_desc: 'Corridor 1: High-capacity rapid transit traversing North Chennai, Anna Salai & Southern Airport Corridor with 26 elevated and underground stations.',
    route_type: 1,
    route_url: 'https://chennaimetrorail.org/route-map/',
    route_color: '#0284C7',
    route_text_color: '#FFFFFF',
    service_category: 'metro_blue',
    origin: 'Wimco Nagar Depot',
    destination: 'Chennai International Airport',
    distance_km: 32.65,
    estimated_duration_min: 54,
    stops_count: 26,
    frequency_peak: 'Every 5 - 6 mins',
    frequency_off_peak: 'Every 8 - 10 mins',
    first_trip: '05:00 AM',
    last_trip: '11:00 PM',
    fare_min: 10,
    fare_max: 50,
    stops_sequence: [
      'Wimco Nagar Depot', 'Wimco Nagar', 'Tiruvottriyur', 'Tollgate', 'New Washermanpet',
      'Washermanpet', 'Mannadi', 'High Court', 'Puratchi Thalaivar Dr. M.G.R Central',
      'Government Estate', 'LIC', 'Thousand Lights', 'AG-DMS', 'Teynampet', 'Nandanam',
      'Saidapet', 'Little Mount', 'Guindy', 'Alandur', 'Nanganallur Road', 'Meenambakkam',
      'Chennai International Airport'
    ],
  },
  {
    route_id: 'CMRL-GREEN',
    agency_id: 'CMRL',
    route_short_name: 'Green Line',
    route_long_name: 'Puratchi Thalaivar Dr. M.G.R Central ⇄ St. Thomas Mount',
    route_desc: 'Corridor 2: Connects Chennai Central, Egmore, Kilpauk, Anna Nagar, Koyambedu CMBT, and Vadapalani through to St. Thomas Mount.',
    route_type: 1,
    route_url: 'https://chennaimetrorail.org/route-map/',
    route_color: '#16A34A',
    route_text_color: '#FFFFFF',
    service_category: 'metro_green',
    origin: 'Chennai Central',
    destination: 'St. Thomas Mount',
    distance_km: 22.0,
    estimated_duration_min: 42,
    stops_count: 17,
    frequency_peak: 'Every 5 - 6 mins',
    frequency_off_peak: 'Every 9 - 12 mins',
    first_trip: '05:00 AM',
    last_trip: '11:00 PM',
    fare_min: 10,
    fare_max: 40,
    stops_sequence: [
      'Puratchi Thalaivar Dr. M.G.R Central', 'Chennai Egmore', 'Nehru Park', 'Kilpauk',
      'Pachaiyappa College', 'Shenoy Nagar', 'Anna Nagar East', 'Anna Nagar Tower',
      'Thirumangalam', 'Koyambedu CMBT', 'CMBT', 'Arumbakkam', 'Vadapalani', 'Ashok Nagar',
      'Ekkattuthangal', 'Alandur', 'St. Thomas Mount'
    ],
  },
  {
    route_id: 'CMRL-INTER',
    agency_id: 'CMRL',
    route_short_name: 'Inter-Corridor Direct',
    route_long_name: 'Puratchi Thalaivar Dr. M.G.R Central ⇄ Airport (via Koyambedu)',
    route_desc: 'Direct loop service linking Chennai Central directly to Chennai International Airport via Koyambedu CMBT and Alandur interchange without train transfer.',
    route_type: 1,
    route_url: 'https://chennaimetrorail.org',
    route_color: '#9333EA',
    route_text_color: '#FFFFFF',
    service_category: 'metro_blue',
    origin: 'Chennai Central (Loop)',
    destination: 'Chennai International Airport',
    distance_km: 35.2,
    estimated_duration_min: 58,
    stops_count: 21,
    frequency_peak: 'Every 15 mins',
    frequency_off_peak: 'Every 20 mins',
    first_trip: '05:30 AM',
    last_trip: '10:30 PM',
    fare_min: 10,
    fare_max: 50,
    stops_sequence: [
      'Puratchi Thalaivar Dr. M.G.R Central', 'Chennai Egmore', 'Kilpauk', 'Shenoy Nagar',
      'Anna Nagar Tower', 'Koyambedu CMBT', 'Vadapalani', 'Ashok Nagar', 'Alandur',
      'Nanganallur Road', 'Meenambakkam', 'Chennai International Airport'
    ],
  },

  // --- MTC BUS ROUTES ---
  {
    route_id: 'MTC-21G',
    agency_id: 'MTC',
    route_short_name: '21G',
    route_long_name: 'Broadway ⇄ Tambaram',
    route_desc: 'Iconic trunk corridor through Marina Beach, Santhome, Adyar, Guindy, Airport & GST Road.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#DC2626',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_deluxe',
    origin: 'Broadway (Parrys)',
    destination: 'Tambaram',
    distance_km: 29.5,
    estimated_duration_min: 75,
    stops_count: 38,
    frequency_peak: 'Every 4 - 8 mins',
    frequency_off_peak: 'Every 10 - 15 mins',
    first_trip: '04:30 AM',
    last_trip: '11:15 PM',
    fare_min: 7,
    fare_max: 28,
    stops_sequence: [
      'Broadway (Parrys)', 'Secretariat', 'Anna Square', 'Marina Beach', 'Santhome Church',
      'Pattinapakkam', 'Foreshore Estate', 'Adyar Depot', 'Malarthottam', 'Guindy Race Course',
      'Guindy Station', 'Kathipara / Alandur', 'Meenambakkam Airport', 'Pallavaram',
      'Chromepet', 'Tambaram Sanatorium', 'Tambaram Bus Terminus'
    ],
  },
  {
    route_id: 'MTC-102',
    agency_id: 'MTC',
    route_short_name: '102',
    route_long_name: 'Broadway ⇄ Kelambakkam',
    route_desc: 'Major coastal & Rajiv Gandhi IT Expressway (OMR) lifeline connecting central Chennai to tech parks and southern suburbs.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#EA580C',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_express',
    origin: 'Broadway (Parrys)',
    destination: 'Kelambakkam',
    distance_km: 36.8,
    estimated_duration_min: 90,
    stops_count: 42,
    frequency_peak: 'Every 7 - 10 mins',
    frequency_off_peak: 'Every 15 mins',
    first_trip: '05:00 AM',
    last_trip: '10:45 PM',
    fare_min: 8,
    fare_max: 35,
    stops_sequence: [
      'Broadway (Parrys)', 'Queen Marys College', 'Santhome', 'Adyar Anandha Bhavan',
      'Adyar Depot', 'Thiruvanmiyur RTO', 'Kandanchavadi IT Zone', 'Perungudi',
      'Thoraipakkam', 'Sholinganallur Junction', 'Navalur', 'Siruseri IT Park', 'Kelambakkam'
    ],
  },
  {
    route_id: 'MTC-570',
    agency_id: 'MTC',
    route_short_name: '570',
    route_long_name: 'CMBT (Koyambedu) ⇄ Siruseri I.T. Park',
    route_desc: 'High-ridership cross-city technology corridor running AC Volvo and Deluxe buses between CMBT bus terminus and SIPCOT IT Park.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#2563EB',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_ac',
    origin: 'CMBT (Koyambedu)',
    destination: 'Siruseri I.T. Park',
    distance_km: 38.2,
    estimated_duration_min: 85,
    stops_count: 36,
    frequency_peak: 'Every 6 - 9 mins',
    frequency_off_peak: 'Every 12 - 15 mins',
    first_trip: '05:15 AM',
    last_trip: '11:00 PM',
    fare_min: 15,
    fare_max: 55,
    stops_sequence: [
      'CMBT (Koyambedu)', 'Vadapalani', 'Ashok Pillar', 'Kasi Theatre', 'Ekkattuthangal',
      'Guindy Industrial Estate', 'Velachery MRTS', 'Taramani CSIR Road', 'Kandanchavadi',
      'Thoraipakkam', 'Sholinganallur', 'Navalur Toll', 'Siruseri I.T. Park'
    ],
  },
  {
    route_id: 'MTC-23C',
    agency_id: 'MTC',
    route_short_name: '23C',
    route_long_name: 'Besant Nagar ⇄ Ayanavaram',
    route_desc: 'Heartland cross-city connection passing through Adyar, Nandanam, T. Nagar commercial center, Chetpet and Kilpauk.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#059669',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_ordinary',
    origin: 'Besant Nagar',
    destination: 'Ayanavaram',
    distance_km: 19.4,
    estimated_duration_min: 55,
    stops_count: 28,
    frequency_peak: 'Every 5 - 8 mins',
    frequency_off_peak: 'Every 10 - 12 mins',
    first_trip: '05:00 AM',
    last_trip: '10:30 PM',
    fare_min: 5,
    fare_max: 18,
    stops_sequence: [
      'Besant Nagar', 'Adyar Depot', 'Kotturpuram', 'Nandanam Signal', 'Vani Mahal',
      'T. Nagar (Panagal Park)', 'Vidyodaya', 'Gemini Flyover', 'Chetpet Station',
      'Kilpauk Medical College', 'Ayanavaram'
    ],
  },
  {
    route_id: 'MTC-29C',
    agency_id: 'MTC',
    route_short_name: '29C',
    route_long_name: 'Besant Nagar ⇄ Perambur',
    route_desc: 'Historic central line passing through Mylapore Luz, Royapettah, Mount Road, and North-Central Chennai neighborhoods.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#D97706',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_ordinary',
    origin: 'Besant Nagar',
    destination: 'Perambur',
    distance_km: 21.0,
    estimated_duration_min: 60,
    stops_count: 32,
    frequency_peak: 'Every 6 - 8 mins',
    frequency_off_peak: 'Every 12 mins',
    first_trip: '05:10 AM',
    last_trip: '10:45 PM',
    fare_min: 5,
    fare_max: 20,
    stops_sequence: [
      'Besant Nagar', 'Adyar Gate', 'Mylapore Luz Corner', 'Royapettah Clock Tower',
      'Express Avenue / Spencers', 'Simpsons / Mount Road', 'Central Station',
      'Pulianthope', 'Perambur Church', 'Perambur Bus Stand'
    ],
  },
  {
    route_id: 'MTC-A1',
    agency_id: 'MTC',
    route_short_name: 'A1',
    route_long_name: 'Puratchi Thalaivar Dr. M.G.R Central ⇄ Thiruvanmiyur',
    route_desc: 'Express coastal route linking Chennai Central rail terminus directly to Southern Beach & Thiruvanmiyur beach/temple.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#E11D48',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_deluxe',
    origin: 'Chennai Central',
    destination: 'Thiruvanmiyur',
    distance_km: 16.5,
    estimated_duration_min: 48,
    stops_count: 24,
    frequency_peak: 'Every 8 - 12 mins',
    frequency_off_peak: 'Every 15 mins',
    first_trip: '05:30 AM',
    last_trip: '11:00 PM',
    fare_min: 8,
    fare_max: 22,
    stops_sequence: [
      'Chennai Central', 'Pallavan Salai', 'Anna Salai LIC', 'Thousand Lights',
      'Gopalapuram', 'Music Academy', 'Alwarpet Signal', 'Adyar Cancer Institute',
      'Adyar Signal', 'Marundeeswarar Temple', 'Thiruvanmiyur Depot'
    ],
  },
  {
    route_id: 'MTC-D70',
    agency_id: 'MTC',
    route_short_name: 'D70',
    route_long_name: 'Ambattur O.T. ⇄ Velachery',
    route_desc: 'Heavy arterial connection bridging Ambattur industrial zone, Koyambedu, Ashok Nagar, Guindy, and Velachery MRTS.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#4F46E5',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_deluxe',
    origin: 'Ambattur O.T.',
    destination: 'Velachery',
    distance_km: 26.8,
    estimated_duration_min: 70,
    stops_count: 34,
    frequency_peak: 'Every 6 - 10 mins',
    frequency_off_peak: 'Every 12 - 16 mins',
    first_trip: '05:00 AM',
    last_trip: '10:30 PM',
    fare_min: 8,
    fare_max: 26,
    stops_sequence: [
      'Ambattur O.T.', 'Ambattur Estate', 'Padi / Lucas TVS', 'Thirumangalam',
      'Koyambedu CMBT', 'Vadapalani', 'Ashok Pillar', 'Ekkattuthangal',
      'Guindy Station', 'Checkpost', 'Velachery Lake', 'Velachery Bus Stand'
    ],
  },
  {
    route_id: 'MTC-19B',
    agency_id: 'MTC',
    route_short_name: '19B',
    route_long_name: 'T. Nagar (Panagal Park) ⇄ Kelambakkam',
    route_desc: 'Direct southern link connecting shoppers and workers from central T. Nagar to Medavakkam, OMR and Kelambakkam.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#0891B2',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_express',
    origin: 'T. Nagar',
    destination: 'Kelambakkam',
    distance_km: 34.0,
    estimated_duration_min: 80,
    stops_count: 38,
    frequency_peak: 'Every 8 - 12 mins',
    frequency_off_peak: 'Every 15 - 20 mins',
    first_trip: '05:15 AM',
    last_trip: '10:45 PM',
    fare_min: 8,
    fare_max: 30,
    stops_sequence: [
      'T. Nagar (Panagal Park)', 'Saidapet', 'Little Mount', 'Guindy', 'Velachery',
      'Pallikaranai Marshland', 'Medavakkam Koot Road', 'Karanai', 'Mambakkam', 'Kelambakkam'
    ],
  },
  {
    route_id: 'MTC-500',
    agency_id: 'MTC',
    route_short_name: '500',
    route_long_name: 'Chengalpattu ⇄ Tambaram',
    route_desc: 'Outer-suburban high-speed express route along the southern GST corridor servicing university campuses and tech corridors.',
    route_type: 3,
    route_url: 'https://mtcbus.tn.gov.in',
    route_color: '#7C3AED',
    route_text_color: '#FFFFFF',
    service_category: 'mtc_express',
    origin: 'Chengalpattu',
    destination: 'Tambaram',
    distance_km: 31.4,
    estimated_duration_min: 50,
    stops_count: 20,
    frequency_peak: 'Every 10 mins',
    frequency_off_peak: 'Every 15 mins',
    first_trip: '04:30 AM',
    last_trip: '11:30 PM',
    fare_min: 10,
    fare_max: 32,
    stops_sequence: [
      'Chengalpattu Old Bus Stand', 'Mahindra World City', 'Singaperumal Koil',
      'Maraimalai Nagar', 'SRM University / Kattankulathur', 'Potheri',
      'Guduvanchery', 'Perungalathur', 'Tambaram MEPZ', 'Tambaram'
    ],
  }
];

export const SEED_STOPS: Stop[] = [
  {
    stop_id: 'ST-CENTRAL',
    stop_code: 'MAS-METRO',
    stop_name: 'Puratchi Thalaivar Dr. M.G.R Central',
    stop_name_tamil: 'புரட்சி தலைவர் டாக்டர் எம்.ஜி.ஆர் சென்ட்ரல்',
    stop_desc: 'Chennai’s premier transportation interchange hub. Connects Chennai Central railway station, Metro Blue Line, Metro Green Line, MRTS & suburban rail.',
    stop_lat: 13.0827,
    stop_lon: 80.2707,
    zone_id: 'ZONE-CENTRAL',
    is_metro_station: true,
    metro_line: 'interchange',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-BLUE', 'CMRL-GREEN', 'CMRL-INTER', 'MTC-A1', 'MTC-29C'],
  },
  {
    stop_id: 'ST-AIRPORT',
    stop_code: 'MAA-METRO',
    stop_name: 'Chennai International Airport',
    stop_name_tamil: 'சென்னை பன்னாட்டு வானூர்தி நிலையம்',
    stop_desc: 'Direct air-conditioned connector to Domestic & International Terminals (T1, T2, T4) via travelator.',
    stop_lat: 12.9818,
    stop_lon: 80.1643,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: true,
    metro_line: 'blue',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-BLUE', 'CMRL-INTER', 'MTC-21G'],
  },
  {
    stop_id: 'ST-ALANDUR',
    stop_code: 'ALN-METRO',
    stop_name: 'Alandur Multi-Modal Interchange',
    stop_name_tamil: 'ஆலந்தூர் பரிமாற்ற நிலையம்',
    stop_desc: 'Two-tier elevated interchange facilitating cross-platform transfers between Blue and Green metro lines, plus Kathipara grade separator bus bays.',
    stop_lat: 13.0039,
    stop_lon: 80.2014,
    zone_id: 'ZONE-CENTRAL',
    is_metro_station: true,
    metro_line: 'interchange',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-BLUE', 'CMRL-GREEN', 'CMRL-INTER', 'MTC-21G'],
  },
  {
    stop_id: 'ST-GUINDY',
    stop_code: 'GND-01',
    stop_name: 'Guindy Station & Industrial Estate',
    stop_name_tamil: 'கிண்டி ரயில் நிலையம் மற்றும் தொழிற்பேட்டை',
    stop_desc: 'Crucial interchange linking suburban rail, Metro Blue line, Race Course & MTC bus terminals heading to OMR and GST Road.',
    stop_lat: 13.0067,
    stop_lon: 80.2025,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: true,
    metro_line: 'blue',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-BLUE', 'MTC-21G', 'MTC-570', 'MTC-D70', 'MTC-19B'],
  },
  {
    stop_id: 'ST-KMB',
    stop_code: 'CMBT-01',
    stop_name: 'Puratchi Thalaivar Dr. M.G.R Bus Terminus (Koyambedu CMBT)',
    stop_name_tamil: 'கோயம்பேடு பேருந்து நிலையம் (சி.எம்.பி.டி)',
    stop_desc: 'One of Asia’s largest bus terminals with extensive intra-state, inter-state, MTC city buses and Metro Green line station.',
    stop_lat: 13.0694,
    stop_lon: 80.1948,
    zone_id: 'ZONE-WEST',
    is_metro_station: true,
    metro_line: 'green',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-GREEN', 'CMRL-INTER', 'MTC-570', 'MTC-D70'],
  },
  {
    stop_id: 'ST-TNAGAR',
    stop_code: 'TNG-01',
    stop_name: 'T. Nagar (Panagal Park & Bus Terminus)',
    stop_name_tamil: 'தி. நகர் (பனகல் பூங்கா & பேருந்து நிலையம்)',
    stop_desc: 'Bustling retail epicenter of Chennai with high-frequency MTC bus services across the metropolis and pedestrian skywalk to Mambalam Railway station.',
    stop_lat: 13.0418,
    stop_lon: 80.2341,
    zone_id: 'ZONE-CENTRAL',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-23C', 'MTC-19B'],
  },
  {
    stop_id: 'ST-THIRU',
    stop_code: 'THV-01',
    stop_name: 'Thiruvanmiyur Bus Depot & RTO',
    stop_name_tamil: 'திருவான்மியூர் பேருந்து பணிமனை',
    stop_desc: 'Southern city terminus connecting ECR beach highway and gateway to Rajiv Gandhi IT Expressway (OMR). Near Marundeeswarar Temple.',
    stop_lat: 12.9830,
    stop_lon: 80.2594,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-102', 'MTC-A1'],
  },
  {
    stop_id: 'ST-TAMBARAM',
    stop_code: 'TBM-01',
    stop_name: 'Tambaram Bus Terminus & Railway Station',
    stop_name_tamil: 'தாம்பரம் பேருந்து நிலையம் & ரயில் நிலையம்',
    stop_desc: 'Gateway to Southern Tamil Nadu and southern suburbs. Junction point for suburban local trains, express long-distance trains, and over 80 MTC routes.',
    stop_lat: 12.9249,
    stop_lon: 80.1000,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-21G', 'MTC-500'],
  },
  {
    stop_id: 'ST-BROADWAY',
    stop_code: 'BWY-01',
    stop_name: 'Broadway Bus Terminus (Parrys Corner)',
    stop_name_tamil: 'பிராட்வே பேருந்து நிலையம் (பாரிஸ் கார்னர்)',
    stop_desc: 'Historic North Chennai transit hub adjacent to High Court Metro Station, Chennai Fort and Port trust.',
    stop_lat: 13.0891,
    stop_lon: 80.2870,
    zone_id: 'ZONE-NORTH',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-21G', 'MTC-102'],
  },
  {
    stop_id: 'ST-VADAPALANI',
    stop_code: 'VDP-METRO',
    stop_name: 'Vadapalani Junction & Metro',
    stop_name_tamil: 'வடபழனி சந்திப்பு மற்றும் மெட்ரோ',
    stop_desc: 'Major film hub, temple neighborhood and retail center with multi-level Metro Green station integrated directly into Forum Vijaya Mall.',
    stop_lat: 13.0500,
    stop_lon: 80.2120,
    zone_id: 'ZONE-WEST',
    is_metro_station: true,
    metro_line: 'green',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-GREEN', 'CMRL-INTER', 'MTC-570', 'MTC-D70'],
  },
  {
    stop_id: 'ST-VELACHERY',
    stop_code: 'VLC-01',
    stop_name: 'Velachery Bus Terminus & MRTS',
    stop_name_tamil: 'வேளச்சேரி பேருந்து நிலையம் மற்றும் எம்.ஆர்.டி.எஸ்',
    stop_desc: 'Crucial southern residential and retail interchange connecting MRTS elevated rail, MTC buses to OMR, Tambaram and Guindy.',
    stop_lat: 12.9759,
    stop_lon: 80.2212,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-570', 'MTC-D70', 'MTC-19B'],
  },
  {
    stop_id: 'ST-SHOLING',
    stop_code: 'SHL-01',
    stop_name: 'Sholinganallur IT Junction',
    stop_name_tamil: 'சோழிங்கநல்லூர் ஐடி சந்திப்பு',
    stop_desc: 'Critical crossroad on OMR (IT Expressway) intersecting with Medavakkam-Tambaram road and future Metro Phase 2 interchange.',
    stop_lat: 12.9010,
    stop_lon: 80.2279,
    zone_id: 'ZONE-OMR',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-102', 'MTC-570'],
  },
  {
    stop_id: 'ST-ADYAR',
    stop_code: 'ADY-01',
    stop_name: 'Adyar Bus Depot & Signal',
    stop_name_tamil: 'அடையாறு பேருந்து பணிமனை',
    stop_desc: 'Prime cultural and transit node along the Adyar river, linking southern beaches to central shopping zones.',
    stop_lat: 13.0064,
    stop_lon: 80.2575,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: false,
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-21G', 'MTC-102', 'MTC-23C', 'MTC-A1'],
  },
  {
    stop_id: 'ST-SIRUSERI',
    stop_code: 'SRS-01',
    stop_name: 'Siruseri SIPCOT I.T. Park',
    stop_name_tamil: 'சிறுசேரி சிப்காட் ஐ.டி பார்க்',
    stop_desc: 'Terminal hub of the Rajiv Gandhi IT Expressway serving TCS, Cognizant and over 70 tech enterprises.',
    stop_lat: 12.8286,
    stop_lon: 80.2173,
    zone_id: 'ZONE-OMR',
    is_metro_station: false,
    interchange_available: false,
    wheelchair_boarding: 1,
    connected_routes: ['MTC-102', 'MTC-570'],
  },
  {
    stop_id: 'ST-EGMORE',
    stop_code: 'EGM-METRO',
    stop_name: 'Chennai Egmore Metro & Rail',
    stop_name_tamil: 'சென்னை எழும்பூர் மெட்ரோ & ரயில் நிலையம்',
    stop_desc: 'Heritage terminal station serving southern and western long-distance trains and Metro Green line.',
    stop_lat: 13.0784,
    stop_lon: 80.2610,
    zone_id: 'ZONE-CENTRAL',
    is_metro_station: true,
    metro_line: 'green',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-GREEN', 'CMRL-INTER'],
  },
  {
    stop_id: 'ST-STMOUNT',
    stop_code: 'STM-METRO',
    stop_name: 'St. Thomas Mount Metro & Suburban',
    stop_name_tamil: 'பரங்கிமலை மெட்ரோ & புறநகர் ரயில் நிலையம்',
    stop_desc: 'Southern terminus for Green Line Metro integrated with suburban local railway and upcoming MRTS extension.',
    stop_lat: 12.9958,
    stop_lon: 80.1983,
    zone_id: 'ZONE-SOUTH',
    is_metro_station: true,
    metro_line: 'green',
    interchange_available: true,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-GREEN'],
  },
  {
    stop_id: 'ST-WIMCO',
    stop_code: 'WMC-METRO',
    stop_name: 'Wimco Nagar Depot & Metro',
    stop_name_tamil: 'விம்கோ நகர் பணிமனை & மெட்ரோ',
    stop_desc: 'Northern terminus of the Blue Line Phase 1 Extension serving the industrial and coastal belt of North Chennai.',
    stop_lat: 13.1678,
    stop_lon: 80.3015,
    zone_id: 'ZONE-NORTH',
    is_metro_station: true,
    metro_line: 'blue',
    interchange_available: false,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-BLUE'],
  },
  {
    stop_id: 'ST-ANNANAGAR',
    stop_code: 'ANT-METRO',
    stop_name: 'Anna Nagar Tower Metro',
    stop_name_tamil: 'அண்ணா நகர் டவர் மெட்ரோ',
    stop_desc: 'Underground Metro Green station nestled directly at the iconic Anna Nagar Tower Park recreational zone.',
    stop_lat: 13.0850,
    stop_lon: 80.2185,
    zone_id: 'ZONE-WEST',
    is_metro_station: true,
    metro_line: 'green',
    interchange_available: false,
    wheelchair_boarding: 1,
    connected_routes: ['CMRL-GREEN'],
  }
];

export const SEED_CALENDAR: Calendar[] = [
  {
    service_id: 'DAILY',
    monday: 1,
    tuesday: 1,
    wednesday: 1,
    thursday: 1,
    friday: 1,
    saturday: 1,
    sunday: 1,
    start_date: '20250101',
    end_date: '20271231',
  },
  {
    service_id: 'WEEKDAY_PEAK',
    monday: 1,
    tuesday: 1,
    wednesday: 1,
    thursday: 1,
    friday: 1,
    saturday: 0,
    sunday: 0,
    start_date: '20250101',
    end_date: '20271231',
  },
  {
    service_id: 'WEEKEND_SPECIAL',
    monday: 0,
    tuesday: 0,
    wednesday: 0,
    thursday: 0,
    friday: 0,
    saturday: 1,
    sunday: 1,
    start_date: '20250101',
    end_date: '20271231',
  }
];
